---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-group-role
  namespace: production
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-group-binding
  namespace: production
subjects:
- kind: Group
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-group-role
  apiGroup: rbac.authorization.k8s.io

---
